server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      # The following are the default timeout settings
      request-connect-timeout: 5000 # 5 seconds Timeout on waiting to connect to the config server (ms)
      request-read-timeout: 5000 # 5 seconds Timeout on waiting to read configuration data from the config server (ms)
      # The following are the default retry settings
      fail-fast: true # Makes a failure to connect to the config server fatal
      retry:
          max-attempts: 6 # Maximum number of attempts to connect to the config server
          initial-interval: 1000 # 1 second Initial interval between attempts to connect to the config server (ms)
          max-interval: 2000 # 2 seconds Maximum interval between attempts to connect to the config server (ms)
          multiplier: 1.1 # Multiplier to apply to the previous interval between attempts to connect to the config server
# The following are the default settings for the config client
management:
  endpoints:  # Expose the /refresh endpoint
    web:
      exposure:
        include: refresh
polar:
  greeting: Welcome to the local book catalog!