name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test # The name of the job
    runs-on: ubuntu-22.04 # The type of machine to run the job on
    permissions:
      contents: read # The job requires read access to the repository
      security-events: write # The job requires write access to security events
    steps: # The steps to run on the job
      - name: Checkout source code # The name of the step
        uses: actions/checkout@v3 # The type of action to run
      - name: Set up JDK 17 # The name of the step
        uses: actions/setup-java@v3 # The type of action to run
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build, unit tests and integration tests # The name of the step
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
